properties:
  body:
    type: object
    properties:
      id:
        type: string
      newState:
        type: string
    required:
      - id
      - newState
    additionalProperties: false
additionalProperties: true
