properties:
  body:
    properties:
      name:
        type: string
      weight:
        type: number
      loading_time:
        type: number
    required:
      - name
      - weight
      - loading_time
    additionalProperties: false
additionalProperties: true